# Set find variables
set(CMAKE_FIND_LIBRARY_PREFIXES lib "" CACHE STRING "" FORCE)
set(CMAKE_FIND_LIBRARY_SUFFIXES .a _stub_weak.a CACHE STRING "" FORCE)

set(CMAKE_OUTPUT_EXTENSION .o)
set(CMAKE_CXX_OUTPUT_EXTENSION .o)
set(CMAKE_OUTPUT_EXTENSION_REPLACE TRUE)
set(CMAKE_CXX_OUTPUT_EXTENSION_REPLACE TRUE)

set(CMAKE_EXECUTABLE_SUFFIX ".elf" CACHE STRING "" FORCE)
set(CMAKE_EXECUTABLE_SUFFIX_C ".elf" CACHE STRING "" FORCE)
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf" CACHE STRING "" FORCE)
