if(NOT CMAKE_PS5PSSL_COMPILE_OBJECT)
    set(CMAKE_PS5PSSL_COMPILE_OBJECT "<CMAKE_PS5PSSL_COMPILER> compile -MD -O3 -fastmath <FLAGS> -o <OBJECT> <SOURCE>")
endif()

if(NOT CMAKE_PS5PSSL_LINK_EXECUTABLE)
    set(CMAKE_PS5PSSL_LINK_EXECUTABLE "<CMAKE_PS5PSSL_COMPILER> link -o <TARGET> <CMAKE_PS5PSSL_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES>" CACHE STRING "" FORCE)
endif()

if(NOT CMAKE_PS5PSSL_CREATE_SHARED_LIBRARY)
  set(CMAKE_PS5PSSL_CREATE_SHARED_LIBRARY "${CMAKE_PS5PSSL_LINK_EXECUTABLE} --oformat=prx")
endif()

if(NOT CMAKE_PS5PSSL_CREATE_SHARED_MODULE)
  set(CMAKE_PS5PSSL_CREATE_SHARED_MODULE ${CMAKE_PS5PSSL_CREATE_SHARED_LIBRARY})
endif()

if(NOT CMAKE_PS5PSSL_CREATE_STATIC_LIBRARY)
  set(CMAKE_PS5PSSL_CREATE_STATIC_LIBRARY "<CMAKE_PS5PSSL_COMPILER> archive rcs <TARGET> <LINK_FLAGS> <OBJECTS>")

  set(CMAKE_PS5PSSL_ARCHIVE_CREATE ${CMAKE_PS5PSSL_CREATE_STATIC_LIBRARY})
  set(CMAKE_PS5PSSL_ARCHIVE_FINISH "")
endif()

set(CMAKE_PS5PSSL_INFORMATION_LOADED 1)
